config/routes.rb
Rails.application.routes.draw do

  get 'checkout/index'

  get 'shopping_cart/index'

  get 'categories/index'

  get 'contacts/index'

  get 'abouts/index'

  get 'product/index'

  get 'product/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/' => 'product#index' , as: 'index'
  
  get '/AboutUs' => 'abouts#index' , as: 'abouts'
  
  get '/ContactUs' => 'contacts#index' , as: 'contacts'
  
  get '/Category' => 'categories#index' , as: 'categories'
  
  get '/product/:id', to: 'product#show', as: 'product_id', number: /\d+/
  
  post '/product/:id' => 'product#add_cart', as: :cart
  
  post '/invoice' => 'checkout#invoice' , as: 'invoice'
  
  get '/cart' => 'shopping_cart#index' , as: 'shoppingcart'
  
  get '/checkout' => 'checkout#index' , as: 'pay'
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    
    has_many :products
    
    validates :name, presence: true
    
    def self.search(keyword)
        where("name LIKE ?", "%#{keyword}%")
    end
    
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :city, presence: true
    validates :province, presence: true
    validates :country, presence: true
    validates :email, presence: true 
    validates :address, presence: true
    validates :postal_code, presence: true
    
    
    def name
        first_name + " " + last_name
    end
    
end

app/models/line_item.rb
class LineItem < ApplicationRecord
    validates :quantity, presence: true
    validates :price, presence: true
    belongs_to :product
    belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord

    belongs_to :customer
    
    validates :customer, presence: true
    validates :status, presence: true
    validates :total_amount, presence: true
    
    
    
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :price, presence: true
    validates :stock_quantity, presence: true
    belongs_to :category
    
    has_attached_file :prodimage, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :prodimage, content_type: /\Aimage\/.*\z/
    
 def prodimage_attributes=(attributes)
     prodimage.clear if has_destroy_flag?(attributes) && !prodimage.dirty?
 end

    def self.search(keyword)
        where("name LIKE ?", "%#{keyword}%")
    end
    
end

app/models/province.rb
class Province < ApplicationRecord
    

    
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  
  def index
    @About = About.all
  end
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  
  
  def index
    
    @product = Product.all
    @categories = Category.all
    @cat = Category.new
    
    if params[:keyword]
      @categories = Category.where("name = ? ", params[:category][:id])
      @product = Product.where("name LIKE '%#{params[:keyword]}%'")#.where("category_id = #{params[:category][:id]}")
      #@categories = Category.search(params[:keyword]).order("name ASC")
    end
    
  end

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
  end
  
  def invoice
    @products = Product.all
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def index
  @Contact = Contact.all
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    @products = Product.all.page(params[:page]).per(5)
    
    if params[:keyword]
      @products = Product.search(params[:keyword]).order("name ASC").page(params[:page]).per(5)
    
    end
    
  end

  def show
    @products = Product.find(params[:id])
  end
  
  def create
    @user = User.create( user_params )
  end
  
  def add_cart
    @product = Product.where("id = #{params[:id]}").first
    if session[:cart].nil?
      session[:cart] = Array.new
    else
      session[:cart].push(@product.id)
    end
  end
  
  
  
  private
  
  def set_product
    @products = Product.find(params[:id])
  end
  
  def product_params
    params.require(:product).permit(:name, :description, :price, :stock_quantity)
  end
  
  def user_params
    params.require(:user).permit(:prodimage)
  end
  
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/views/abouts/index.html.erb
<% @About.each do |ab|  %>

<h1><%=ab.title %></h1>
<p><%=ab.message %></p>

<% end %>

app/views/categories/index.html.erb
<h1>Categories</h1>

 <%= form_tag categories_path, :method => "get" do %>
   <%= text_field_tag :keyword %>
   <%= submit_tag 'Search' %>


 <%= form_for @cat do |f| %>

  <%= f.collection_select(:id, @categories, :name, :name) %> 


    <% @categories.each do |cats|%>
        <h2><%=cats.name%></h2>
        <% @product.where("category_id = #{cats.id}").each do |prod| %>
            <h4><%= prod.name %></h4>
            <p><strong>Description:</strong> <%= prod.description %> <strong>Item price:</strong> <%= prod.price %> <strong>Item quantity:</strong> <%= prod.stock_quantity %></p>
            
        
        <% end %>
        
    <% end %>

  <% end %>
 <% end %> 

app/views/contacts/index.html.erb
<% @Contact.each do |ct|  %>

<h1><%=ct.title %></h1>
<p><%=ct.message %></p>


<% end %>

app/views/product/_product.html.erb
<div>
    <% if display_product_link %>
        <%= link_to product.name, product_id_path(product) %>
    <% else %>
        <p><strong>Item:</strong> <%= product.name %></p>
        <p><strong>Description:</strong> <%= product.description %></p>
        <p><strong>Item price:</strong> <%= product.price %></p>
        <p><strong>Item quantity:</strong> <%= product.stock_quantity %></p>
        <p><%= image_tag product.prodimage.url %></p>
    <% end %>
    
    
    
</div>

app/views/product/index.html.erb
<h1>Products</h1>

<%= form_tag index_path, :method => "get" do %>
   <%= text_field_tag :keyword %>
   <%= submit_tag 'Search' %>
 <% end %>
 
<%= paginate @products %>




<%= render partial: 'product',
collection: @products,
locals: {display_product_link: true} %>

<p></p>
<p></p>

<%= link_to 'About', abouts_path %>
<%= link_to 'Contact Us', contacts_path %>
<%= link_to 'Category' , categories_path %>
<%= link_to 'Cart' , shoppingcart_path %>

app/views/product/show.html.erb
<h1>Product</h1>

<%= render partial: 'product',
object: @products,
locals: {display_product_link: false} %>

<%= link_to "Add to Cart", cart_path, :method => "add_cart" %>